
# WiFi
WIFI_SSID = "<your WIFI ssid>"
WIFI_PASSWORD = "<your WIFI password>"

# MQTT
MQTT_BROKER = "<your MQTT broker>"
MQTT_USER = "<your MQTT username>"
MQTT_PASSWORD = "<your MQTT password>"

MQTT_PUBLISH_TOPIC = "<pet>/food/state"
MQTT_SUBSCRIBE_TOPIC = "<pet>/food/action"
